/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RouteCostsRouteImport } from './routes/route-costs'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as AdrsRouteImport } from './routes/adrs'
import { Route as IndexRouteImport } from './routes/index'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteCostsRoute = RouteCostsRouteImport.update({
  id: '/route-costs',
  path: '/route-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdrsRoute = AdrsRouteImport.update({
  id: '/adrs',
  path: '/adrs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adrs': typeof AdrsRoute
  '/audits': typeof AuditsRoute
  '/docs': typeof DocsRoute
  '/lessons': typeof LessonsRoute
  '/maintenance': typeof MaintenanceRoute
  '/milestones': typeof MilestonesRoute
  '/packages': typeof PackagesRoute
  '/patterns': typeof PatternsRoute
  '/route-costs': typeof RouteCostsRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adrs': typeof AdrsRoute
  '/audits': typeof AuditsRoute
  '/docs': typeof DocsRoute
  '/lessons': typeof LessonsRoute
  '/maintenance': typeof MaintenanceRoute
  '/milestones': typeof MilestonesRoute
  '/packages': typeof PackagesRoute
  '/patterns': typeof PatternsRoute
  '/route-costs': typeof RouteCostsRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adrs': typeof AdrsRoute
  '/audits': typeof AuditsRoute
  '/docs': typeof DocsRoute
  '/lessons': typeof LessonsRoute
  '/maintenance': typeof MaintenanceRoute
  '/milestones': typeof MilestonesRoute
  '/packages': typeof PackagesRoute
  '/patterns': typeof PatternsRoute
  '/route-costs': typeof RouteCostsRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adrs'
    | '/audits'
    | '/docs'
    | '/lessons'
    | '/maintenance'
    | '/milestones'
    | '/packages'
    | '/patterns'
    | '/route-costs'
    | '/search'
    | '/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adrs'
    | '/audits'
    | '/docs'
    | '/lessons'
    | '/maintenance'
    | '/milestones'
    | '/packages'
    | '/patterns'
    | '/route-costs'
    | '/search'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/adrs'
    | '/audits'
    | '/docs'
    | '/lessons'
    | '/maintenance'
    | '/milestones'
    | '/packages'
    | '/patterns'
    | '/route-costs'
    | '/search'
    | '/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdrsRoute: typeof AdrsRoute
  AuditsRoute: typeof AuditsRoute
  DocsRoute: typeof DocsRoute
  LessonsRoute: typeof LessonsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MilestonesRoute: typeof MilestonesRoute
  PackagesRoute: typeof PackagesRoute
  PatternsRoute: typeof PatternsRoute
  RouteCostsRoute: typeof RouteCostsRoute
  SearchRoute: typeof SearchRoute
  SessionsRoute: typeof SessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-costs': {
      id: '/route-costs'
      path: '/route-costs'
      fullPath: '/route-costs'
      preLoaderRoute: typeof RouteCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adrs': {
      id: '/adrs'
      path: '/adrs'
      fullPath: '/adrs'
      preLoaderRoute: typeof AdrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdrsRoute: AdrsRoute,
  AuditsRoute: AuditsRoute,
  DocsRoute: DocsRoute,
  LessonsRoute: LessonsRoute,
  MaintenanceRoute: MaintenanceRoute,
  MilestonesRoute: MilestonesRoute,
  PackagesRoute: PackagesRoute,
  PatternsRoute: PatternsRoute,
  RouteCostsRoute: RouteCostsRoute,
  SearchRoute: SearchRoute,
  SessionsRoute: SessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
